services:
  hub-nginx:
    image: nginx:latest
    container_name: game-hub
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - game-network

  shared-db:
    image: mysql:8.0
    container_name: shared-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kkutu_db
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
      - ./modules/KKUTU/db-init/korean_kr.sql:/docker-entrypoint-initdb.d/korean_kr.sql
    networks:
      - game-network

  # 캐치마인드
  catchmind-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: modules/catchMind
        MODULE_NAME: catchMind
    container_name: catchmind-app
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/catchmind

      - SPRING_DATASOURCE_URL=jdbc:mysql://shared-db:3306/catchmind_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - game-network


  # 끄투
  kkutu-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: modules/KKUTU
        MODULE_NAME: KKUTU
    container_name: kkutu-app
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/KKUTU

      - SPRING_DATASOURCE_URL=jdbc:mysql://shared-db:3306/kkutu_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - game-network
    env_file:
      - ./modules/KKUTU/.env

  # 오목
  oh_mock-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: modules/Oh_Mock
        MODULE_NAME: Oh_Mock
    container_name: Oh_Mock-app
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/Oh_Mock

      - SPRING_DATASOURCE_URL=jdbc:mysql://shared-db:3306/oh_mock_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - game-network


  yacht_dice-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: modules/Yacht_Dice
        MODULE_NAME: Yacht_Dice
    container_name: yacht_dice-app
    restart: always
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/Yacht_Dice
      - API_URL=http://member-app:8080/internal/api
    networks:
      - game-network


  indian_poker-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: modules/indian_poker
        MODULE_NAME: indian_poker
    container_name: indian_poker-app
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/indian_poker
    networks:
      - game-network

  mahe-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: modules/mahe
        MODULE_NAME: mahe
    container_name: mahe-app
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/mahe
    networks:
      - game-network

  uno-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: modules/UNO
        MODULE_NAME: UNO
    container_name: uno-app
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/UNO
    networks:
      - game-network

  clue-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: modules/Clue
        MODULE_NAME: Clue
    container_name: clue-app
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/Clue
    networks:
      - game-network

  member-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: member
        MODULE_NAME: member
    container_name: member-app
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://shared-db:3306/member_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=yeedochi_minigames_secret_key_very_long_random_string_1234
    networks:
      - game-network
    volumes:
      - ./uploads:/app/uploads


  templates-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_PATH: templates
        MODULE_NAME: templates
    container_name: templates-app
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/templates
      - API_URL=http://member-app:8080/internal/api
    networks:
      - game-network

networks:
  game-network:
    driver: bridge

volumes:
  db-data: