name: CI/CD Multi-Module Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # [1] Member (ê³µí†µ/ì¸ì¦)
          - module: member
            path: member
            image_name: mini-member

          # [2] Yacht Dice (ê²Œìž„)
          - module: Yacht_Dice
            path: modules/Yacht_Dice
            image_name: mini-yacht

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Check for changes
        id: check
        run: |
          if git diff --quiet HEAD^ HEAD -- ${{ matrix.path }} common; then
            echo "âœ… No changes in ${{ matrix.module }}. Skipping build."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "ðŸš€ Changes detected in ${{ matrix.module }}!"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        if: steps.check.outputs.changed == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        if: steps.check.outputs.changed == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.image_name }}:latest
          build-args: |
            MODULE_PATH=${{ matrix.path }}
            MODULE_NAME=${{ matrix.module }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/app
            sudo chown -R $USER:$USER .
            git init > /dev/null 2>&1 || true
            git remote add origin https://github.com/YeeDochi/minigames.git > /dev/null 2>&1 || true
            git fetch --all
            git reset --hard origin/main
            git sparse-checkout init --cone
            git sparse-checkout set docker-compose.yml nginx db
            
            git pull origin main
            rm -f docker-compose.override.yml
            docker compose pull
            
            docker compose up -d --remove-orphans
            
            docker compose restart hub-nginx
            
            docker image prune -f